version: '2'
services:
    skyrider26application-app:
        image: skyrider26application
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://skyrider26application-postgresql:5432/Skyrider26Application
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=skyrider26application-elasticsearch:9300
        ports:
            - 8080:8080
    skyrider26application-postgresql:
        extends:
            file: postgresql.yml
            service: skyrider26application-postgresql
    skyrider26application-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: skyrider26application-elasticsearch
